---
driver:
  name: ec2
  aws_ssh_key_id: Nik10SecurityKey
  region: ap-south-1
  availability_zone: ap-south-1a
  require_chef_omnibus: true
  security_group_ids: sg-64b9100f
  subnet_id: subnet-f66dd19e
  associate_public_ip: true
  interface: dns

provisioner:
  name: chef_zero

platforms:
  - name: redhat
    driver:
      image_id: 'ami-e60e5a89'
    transport:
      username: 'ec2-user'
      ssh_key: '/tmp/Nik10SecurityKey.pem'

suites:
  - name: default
    run_list:
      - recipe[chef_test::default]
    attributes:

